In [1]:
import os

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import datasets, layers, optimizers

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

# tf.maximum/tf.minimum/tf.clip_by_value
限幅

In [2]:
a = tf.reshape(tf.range(12), [3, 4])
a

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [4]:
tf.maximum(a, 2) # 使所有元素不小于2

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 2,  2,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [6]:
tf.minimum(a, 5) # 使所有元素不大于5

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 1, 2, 3],
       [4, 5, 5, 5],
       [5, 5, 5, 5]])>

In [9]:
tf.clip_by_value(a, 2, 5) # 使所有元素都在这个范围内

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 2, 2, 3],
       [4, 5, 5, 5],
       [5, 5, 5, 5]])>

## 12.2 tf.nn.relu

In [10]:
a = tf.random.normal([3, 3])
a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.07020266,  0.11454783, -0.18235616],
       [-0.5748097 ,  0.75478715,  0.44480723],
       [-0.8876979 , -0.91257536,  0.7949659 ]], dtype=float32)>

In [11]:
tf.nn.relu(a)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.07020266, 0.11454783, 0.        ],
       [0.        , 0.75478715, 0.44480723],
       [0.        , 0.        , 0.7949659 ]], dtype=float32)>

## 12.3 tf.clip_by_norm

In [18]:
a = tf.random.normal([3, 3], mean=10)
a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 7.658079, 10.538096,  8.631984],
       [ 8.988287, 10.62752 ,  8.963372],
       [ 9.352146, 10.704467,  9.311233]], dtype=float32)>

In [20]:
tf.norm(a)

<tf.Tensor: shape=(), dtype=float32, numpy=28.408302>

In [22]:
aa = tf.clip_by_norm(a, 1) # 将a的2范数缩放到1，这种缩放不会改变向量的方向
aa

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.26957187, 0.3709513 , 0.30385426],
       [0.31639647, 0.37409908, 0.31551945],
       [0.32920468, 0.3768077 , 0.32776448]], dtype=float32)>

In [23]:
tf.norm(aa)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99999994>