In [1]:
import os

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import datasets, layers, optimizers

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

In [2]:
a = tf.fill([2, 3], 2.0)

In [3]:
tf.math.log(a)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.6931472, 0.6931472, 0.6931472],
       [0.6931472, 0.6931472, 0.6931472]], dtype=float32)>

In [4]:
tf.exp(a)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[7.389056, 7.389056, 7.389056],
       [7.389056, 7.389056, 7.389056]], dtype=float32)>

In [8]:
tf.math.log(100.0) / tf.math.log(10.0)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [9]:
a = tf.fill([2, 3], 2.0)

In [16]:
a ** 2, tf.pow(a, 3), tf.sqrt(a)

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[4., 4., 4.],
        [4., 4., 4.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[8., 8., 8.],
        [8., 8., 8.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1.4142137, 1.4142137, 1.4142137],
        [1.4142137, 1.4142137, 1.4142137]], dtype=float32)>)

In [20]:
a = tf.fill([2, 3], 2.0)
b = tf.fill([3, 3], 3.0)
a, b, a @ b

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[2., 2., 2.],
        [2., 2., 2.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[18., 18., 18.],
        [18., 18., 18.]], dtype=float32)>)

---
X@W+B

In [96]:
X = tf.cast(tf.reshape(tf.range(50), [10, 5]), tf.float32)
W = tf.random.normal([5, 1])
B = tf.random.normal([10, 1])
tf.nn.relu(X@W+B)

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[ 4.3082886],
       [ 8.169115 ],
       [14.341063 ],
       [17.67097  ],
       [23.040207 ],
       [25.52861  ],
       [32.497944 ],
       [33.98273  ],
       [41.130486 ],
       [47.78525  ]], dtype=float32)>