In [1]:
import os

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import datasets, layers, optimizers

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

## 15.1 创建单层

In [40]:
dense = tf.keras.layers.Dense(2)

In [41]:
dense.build(input_shape=[3, 5])

In [42]:
dense.kernel, dense.bias # 权重

(<tf.Variable 'kernel:0' shape=(5, 2) dtype=float32, numpy=
 array([[-0.35883677,  0.61218846],
        [-0.60147965, -0.6774914 ],
        [-0.4706975 ,  0.3543769 ],
        [ 0.36547863, -0.18171227],
        [ 0.17335379,  0.12288344]], dtype=float32)>,
 <tf.Variable 'bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>)

In [44]:
x = tf.random.uniform([3, 5], maxval=10)

In [45]:
dense(x)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ -4.274965 ,  -2.3277364],
       [-10.026539 ,   2.6969688],
       [ -5.9500647,  -4.0947437]], dtype=float32)>

## 15.2 多层

In [48]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(2),
])

In [49]:
model.build(input_shape=[None, 5]) # 根据输入维度构建模型的权重

In [50]:
model.summary() # 输出

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 10)                60        
                                                                 
 dense_13 (Dense)            (None, 10)                110       
                                                                 
 dense_14 (Dense)            (None, 2)                 22        
                                                                 
Total params: 192
Trainable params: 192
Non-trainable params: 0
_________________________________________________________________


In [39]:
for p in model.trainable_variables: # 得到具体的权重
    print(p.name, p.shape)

dense_8/kernel:0 (5, 10)
dense_8/bias:0 (10,)
dense_9/kernel:0 (10, 10)
dense_9/bias:0 (10,)
dense_10/kernel:0 (10, 2)
dense_10/bias:0 (2,)
