In [1]:
import os

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import datasets, layers, optimizers

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

In [2]:
a = tf.random.normal([4, 28, 28, 3])
tf.reshape(a, [4, 784, 3]).shape

TensorShape([4, 784, 3])

In [3]:
tf.reshape(a, [4, -1, 3]).shape  # -1会自动计算 4*28*28*3/4/3 只能有一个-1

TensorShape([4, 784, 3])

In [4]:
tf.reshape(a, [4, 784 * 3]).shape

TensorShape([4, 2352])

In [5]:
tf.reshape(a, [4, -1]).shape

TensorShape([4, 2352])

In [6]:
a = tf.reshape(tf.range(3 * 4), [3, 4])
a

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [7]:
tf.transpose(a)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])>

In [8]:
a = tf.random.normal([4, 3, 2, 1])

In [9]:
tf.transpose(a).shape

TensorShape([1, 2, 3, 4])

In [10]:
tf.transpose(a, perm=[0, 1, 3, 2]).shape # 仅2，3维度交换

TensorShape([4, 3, 1, 2])

In [11]:
a = tf.random.normal([4, 28, 28, 3]) # b, h, w, c

In [12]:
tf.transpose(a, perm=[0, 3, 1, 2]).shape # b, c, h, w

TensorShape([4, 3, 28, 28])

In [13]:
a = tf.random.normal([4, 35, 8])

In [14]:
tf.expand_dims(a, axis=0).shape # 在0号轴前增加一个维度

TensorShape([1, 4, 35, 8])

In [15]:
tf.expand_dims(a, axis=3).shape # 在3号轴前增加一个维度

TensorShape([4, 35, 8, 1])

In [16]:
tf.expand_dims(a, axis=-1).shape # 在-1号轴后增加一个维度

TensorShape([4, 35, 8, 1])

In [17]:
a = tf.random.normal([4, 35, 8])

In [18]:
a = tf.ones([1, 2, 1, 1, 3])

In [19]:
tf.squeeze(a).shape # 去除所有轴维度为1的维度

TensorShape([2, 3])

In [20]:
tf.squeeze(a, axis=-2).shape # 除第-2轴维度为1的维度

TensorShape([1, 2, 1, 3])

In [21]:
tf.constant([
    [0, 0, 0],
    [10, 10, 10],
    [20, 20, 20],
    [30, 30, 30],
]) + tf.constant([0, 1, 2])

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])>

In [22]:
tf.constant([[0], [10], [20], [30]]) + tf.constant([0, 1, 2])

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])>