In [1]:
import os

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import datasets, layers, optimizers

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

## 9.1 tf.norm 范数

In [2]:
a = tf.ones([2, 2])

In [5]:
tf.norm(a) # 2范数

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [6]:
tf.sqrt(tf.reduce_sum(tf.square(a)))

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [7]:
a = tf.ones([4, 28, 28, 3])

In [8]:
tf.norm(a) # 2范数

<tf.Tensor: shape=(), dtype=float32, numpy=96.99484>

In [9]:
tf.sqrt(tf.reduce_sum(tf.square(a)))

<tf.Tensor: shape=(), dtype=float32, numpy=96.99484>

In [19]:
a =tf.cast(tf.reshape(tf.range(4), (2, 2)), tf.float32)
tf.norm(a, ord=2, axis=0) # 2范数

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.       , 3.1622777], dtype=float32)>

In [20]:
a =tf.cast(tf.reshape(tf.range(4), (2, 2)), tf.float32)
tf.norm(a, ord=1) # 1范数

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

## 9.2 tf.reduce_min/max/mean

In [22]:
a=tf.random.normal([4, 10])

In [23]:
tf.reduce_min(a), tf.reduce_max(a), tf.reduce_mean(a)

(<tf.Tensor: shape=(), dtype=float32, numpy=-2.4114013>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.6764292>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-0.15331738>)

In [24]:
tf.reduce_min(a, axis=0), tf.reduce_max(a, axis=0), tf.reduce_mean(a, axis=0)

(<tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([ 0.13398157, -0.52785397, -1.3379987 , -0.83471185, -0.92672974,
        -1.8742781 , -2.4114013 , -2.296062  , -0.7483747 , -1.465123  ],
       dtype=float32)>,
 <tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([ 1.1284257 ,  0.7317023 ,  0.00485165,  0.7638327 ,  0.471395  ,
         1.632448  , -1.0225589 ,  0.6605299 ,  1.5836227 ,  1.6764292 ],
       dtype=float32)>,
 <tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([ 0.5026103 ,  0.10862198, -0.5793894 ,  0.31661952, -0.19494459,
        -0.20906633, -1.5454205 , -0.5295315 ,  0.6991471 , -0.10182035],
       dtype=float32)>)

In [25]:
tf.reduce_min(a, axis=1), tf.reduce_max(a, axis=1), tf.reduce_mean(a, axis=1)

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-2.4114013, -1.7098228, -1.8742781, -1.465123 ], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.6764292, 1.0600609, 1.5836227, 1.632448 ], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([-0.46801162, -0.42890015,  0.16559246,  0.11804976], dtype=float32)>)

## 9.2 tf.argmax/argmin

最大值/最小值的位置

In [81]:
a=tf.random.normal([4, 3])

In [82]:
c = tf.argmax(a, axis=0)

In [83]:
a, c

(<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[-0.83412164, -0.5170489 , -0.49326763],
        [ 0.08761435,  0.05244758,  0.59934646],
        [ 1.1180947 , -0.59439176, -0.17449789],
        [ 1.0198526 ,  1.3675216 , -0.9054129 ]], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 3, 1], dtype=int64)>)

## 9.3 tf.equal

比较

In [89]:
a = tf.constant([1, 1, 3, 2, 5])
b = tf.range(5)

In [92]:
res = tf.equal(a, b) 
res

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([False,  True, False, False, False])>

In [94]:
same = tf.reduce_sum(tf.cast(res, dtype=tf.int32))
same

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [96]:
same/b.shape[0]

<tf.Tensor: shape=(), dtype=float64, numpy=0.2>

In [98]:
a = tf.constant([
    [0.1, 0.2, 0.7],
    [0.9, 0.05, 0.05]
])

In [100]:
pred = tf.cast(tf.argmax(a, axis=1), dtype=tf.int32)
pred

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 0])>

In [101]:
y = tf.constant([2, 1])

In [104]:
correct = tf.reduce_sum(tf.cast(tf.equal(y, pred), dtype=tf.int32))
correct

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [105]:
correct/y.shape[0]

<tf.Tensor: shape=(), dtype=float64, numpy=0.5>

## 9.4 tf.unique

去重

In [106]:
a = tf.range(5)

In [107]:
tf.unique(a)

Unique(y=<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>, idx=<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>)

In [112]:
a = tf.constant([3, 2, 2, 3, 1])
unique, index = tf.unique(a)
unique, index # unique为不重复元素，index为不重复元素在原Tensor的下标

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 2, 1])>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 1, 0, 2])>)

In [114]:
tf.gather(unique, index) # 可以使用tf.gather来还原

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([3, 2, 2, 3, 1])>