In [1]:
import os

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import datasets, layers, optimizers

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

## 17.1 MSE

均方差

In [3]:
y = tf.constant([1, 2, 3, 0, 2])
y = tf.one_hot(y, depth=4)
y

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]], dtype=float32)>

In [4]:
out = tf.random.normal([5, 4])

In [5]:
loss1 = tf.reduce_mean(tf.square(y-out))

In [6]:
loss2 = tf.square(tf.norm(y-out))/(5*4)

In [7]:
loss3 = tf.reduce_mean(tf.losses.MSE(y, out))

In [8]:
loss1, loss2, loss3

(<tf.Tensor: shape=(), dtype=float32, numpy=1.1351672>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.1351674>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.1351672>)

## 17.2 Entropy
交叉熵

In [95]:
a = tf.constant([0.1, 0.1, 0.1, 0.7])
-tf.reduce_sum(a*tf.math.log(a)/tf.math.log(2.)) # 计算熵

<tf.Tensor: shape=(), dtype=float32, numpy=1.3567796>

In [84]:
a = tf.constant(0.1)
-tf.math.log(a)/tf.math.log(2.) # 计算熵

<tf.Tensor: shape=(), dtype=float32, numpy=3.321928>

In [97]:
a = tf.constant([0.01, 0.01, 0.01, 0.97])
-tf.reduce_sum(a*tf.math.log(a)/tf.math.log(2.)) # 计算熵

<tf.Tensor: shape=(), dtype=float32, numpy=0.24194068>

In [98]:
a = tf.fill([4], 0.25)
-tf.reduce_sum(a*tf.math.log(a)/tf.math.log(2.)) # 计算熵

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [100]:
tf.losses.binary_crossentropy([0], [0.1]) # 二分类交叉熵损失函数

<tf.Tensor: shape=(), dtype=float32, numpy=0.10536041>

In [99]:
tf.losses.binary_crossentropy([0, 1], [0.1, 0.5]) # 二分类交叉熵损失函数

<tf.Tensor: shape=(), dtype=float32, numpy=0.39925367>

In [79]:
tf.losses.categorical_crossentropy([0, 0, 0, 1], [0.01, 0.01, 0.01, 0.97]) # 多分类交叉熵损失函数

<tf.Tensor: shape=(), dtype=float32, numpy=0.030459179>