In [1]:
import os

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import datasets, layers, optimizers

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

In [2]:
a = tf.range(5)
b = tf.Variable(a)  # 可求导
b.name  #  isinstance(b, tf.Variable)

'Variable:0'

In [3]:
b.trainable  #  True
isinstance(b, tf.Tensor)  #  False
isinstance(b, tf.Variable)  #  True

True

In [4]:
tf.is_tensor(b)  #

True

In [5]:
b.numpy()

array([0, 1, 2, 3, 4])

In [6]:
a = tf.ones([])
a.numpy()

1.0

In [7]:
int(a)

1

In [8]:
tf.convert_to_tensor([2.0, 3.0])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [9]:
tf.convert_to_tensor(
    [
        [2.0, 3.0],
        [3.0, 3.0],
    ]
)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [3., 3.]], dtype=float32)>

In [10]:
tf.zeros([])

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [11]:
tf.zeros([2])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [12]:
tf.zeros([2, 2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [13]:
tf.zeros([3, 2, 2])

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]], dtype=float32)>

In [14]:
a = tf.zeros([2, 3, 1])
tf.zeros_like(a)

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]], dtype=float32)>

In [15]:
tf.fill([2, 2], 0.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [16]:
tf.fill([3, 4], 1.0)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [17]:
tf.random.normal([9, 9], mean=1, stddev=1)

<tf.Tensor: shape=(9, 9), dtype=float32, numpy=
array([[-0.3339622 ,  0.75590384,  0.18224335,  0.9677394 ,  2.6427197 ,
         0.6850953 ,  1.136036  ,  0.95062476,  1.9559512 ],
       [ 0.7986677 ,  2.1920934 ,  0.6582104 ,  2.6885676 ,  0.37657475,
        -0.02818227,  0.2481075 ,  0.2772358 , -0.64013064],
       [ 0.36134815, -0.18149173,  0.75193965,  0.5247792 , -0.08223367,
         0.8000775 ,  0.09232879,  0.44062203,  1.3852981 ],
       [ 1.7023351 ,  2.1588268 , -0.14277518,  0.802749  ,  0.5679035 ,
         0.10957009,  1.863265  ,  1.1120352 ,  2.353189  ],
       [ 2.6375194 ,  0.9030762 , -1.0221014 ,  1.5979246 ,  4.236225  ,
        -0.34426427, -0.6666628 ,  0.45898914, -0.03286362],
       [ 2.625897  ,  0.41844553,  1.168549  ,  0.36456126,  1.092748  ,
         0.11698294, -0.06254768, -1.1034572 ,  1.2255988 ],
       [ 3.0852718 ,  1.2086874 ,  0.6275665 ,  0.8544001 ,  1.6359099 ,
         1.1594927 , -1.8929546 ,  1.1529806 ,  1.6010151 ],
       [ 1.620

In [18]:
tf.random.truncated_normal([9, 9], mean=1, stddev=1)

<tf.Tensor: shape=(9, 9), dtype=float32, numpy=
array([[-0.03926754,  1.0289121 ,  1.5943975 ,  1.6976842 , -0.96167886,
         0.4125557 ,  0.59629047,  1.6278063 , -0.00297105],
       [ 1.290344  ,  1.956249  ,  0.38032287, -0.10670018,  0.12816429,
         0.04369414,  0.54304254,  1.0143846 ,  2.6927586 ],
       [ 1.2320317 ,  1.4115856 ,  0.6769426 , -0.26847708,  0.26883918,
         2.8755457 ,  0.7309648 ,  1.9426801 , -0.0154928 ],
       [ 0.35756314,  2.1670508 ,  1.331814  ,  0.55952656, -0.61168814,
         1.0617042 , -0.19327271,  0.46537971,  2.09517   ],
       [ 2.5413156 ,  1.5136058 ,  2.0986314 ,  0.16810954,  0.68922246,
         0.16909027,  2.3874884 ,  1.8591075 ,  0.09613776],
       [ 1.7609817 ,  0.75311613,  1.8823229 ,  2.4635744 ,  0.6133821 ,
         1.73644   ,  0.47279674,  1.4115747 ,  0.44349176],
       [ 2.5777926 ,  2.4773598 ,  1.5585812 ,  1.5340633 ,  0.88619685,
         0.40715498,  1.2927969 ,  1.8869174 ,  1.9335877 ],
       [ 0.662

In [19]:
tf.random.uniform([2, 2], minval=0, maxval=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.4470302 , 0.99127614],
       [0.61278176, 0.7366992 ]], dtype=float32)>

In [20]:
a = tf.range(10)
tf.random.shuffle(a)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([8, 2, 9, 3, 0, 4, 7, 5, 6, 1])>

In [21]:
x = tf.range(10)
y = tf.range(10)
idx = tf.range(x.shape[0])
idx = tf.random.shuffle(idx)
x = tf.gather(x, idx)
y = tf.gather(y, idx)
x, y

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([7, 6, 3, 0, 4, 1, 8, 2, 5, 9])>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([7, 6, 3, 0, 4, 1, 8, 2, 5, 9])>)

In [22]:
x.shape[0]

10

In [23]:
tf.constant(1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [24]:
tf.constant([1])

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1])>

In [25]:
tf.constant([23, 32])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([23, 32])>

In [26]:
tf.constant(
    [
        [2.0, 3.0],
        [3.0, 3.0],
    ]
)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [3., 3.]], dtype=float32)>

In [27]:
a = tf.random.uniform([3, 3])
a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.8589629 , 0.74680305, 0.24932384],
       [0.7433075 , 0.17519057, 0.5762267 ],
       [0.20296109, 0.28385186, 0.4257202 ]], dtype=float32)>

In [28]:
a = tf.range(10)
a = tf.reshape(a, (10,))
# a = tf.one_hot(a, depth=10)
a

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [29]:
a = tf.range(4)
a = tf.reshape(a, (2, 2))
b = tf.range(2)
c = tf.reshape(b, (2, 1))
a, b, c, a @ c

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[0, 1],
        [2, 3]])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1])>,
 <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[0],
        [1]])>,
 <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[1],
        [3]])>)

In [30]:
b = tf.constant([0, 3, 4, 5, 5])
tf.one_hot(b, depth=13)

<tf.Tensor: shape=(5, 13), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)>

In [31]:
out = tf.random.uniform([4, 2])
y = tf.range(4)
y = tf.one_hot(y, depth=2)
loss = tf.keras.losses.mse(y, out)
m = tf.reduce_mean(loss)
out, y, loss, m

(<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.71795917, 0.50509465],
        [0.5269016 , 0.8482598 ],
        [0.00538146, 0.06584084],
        [0.79319966, 0.5977236 ]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[1., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.16733381, 0.1503252 , 0.00218199, 0.4932196 ], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.20326516>)

In [32]:
out = tf.random.uniform([4, 2])
y = tf.range(4)
y = tf.one_hot(y, depth=2)
loss = tf.keras.losses.mse(y, out)
out, y, loss

(<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.27147436, 0.36639202],
        [0.51479816, 0.8535249 ],
        [0.24758053, 0.72304165],
        [0.663761  , 0.16372573]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[1., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.33249637, 0.14323606, 0.29204267, 0.23369241], dtype=float32)>)

In [33]:
a = tf.range(5)
a, tf.reduce_mean(a)

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [34]:
net = layers.Dense(10)
net.build((4, 784))
net.kernel

<tf.Variable 'kernel:0' shape=(784, 10) dtype=float32, numpy=
array([[-0.02951557, -0.07177003, -0.02408069, ...,  0.08507853,
         0.00081721, -0.00265571],
       [-0.01964413,  0.06023789,  0.05487295, ..., -0.0071638 ,
         0.02506561, -0.02076587],
       [ 0.06763835,  0.00176254, -0.04254898, ..., -0.00888922,
        -0.0770338 ,  0.05714805],
       ...,
       [-0.00804092,  0.08497003, -0.05595911, ..., -0.01711814,
        -0.04232854, -0.05476615],
       [ 0.05068586, -0.007269  , -0.04129183, ..., -0.00616296,
        -0.01938014, -0.08653193],
       [ 0.02608956, -0.08575377,  0.04481799, ..., -0.01034772,
        -0.02418967, -0.00737866]], dtype=float32)>

In [35]:
net.bias

<tf.Variable 'bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [36]:
net.kernel

<tf.Variable 'kernel:0' shape=(784, 10) dtype=float32, numpy=
array([[-0.02951557, -0.07177003, -0.02408069, ...,  0.08507853,
         0.00081721, -0.00265571],
       [-0.01964413,  0.06023789,  0.05487295, ..., -0.0071638 ,
         0.02506561, -0.02076587],
       [ 0.06763835,  0.00176254, -0.04254898, ..., -0.00888922,
        -0.0770338 ,  0.05714805],
       ...,
       [-0.00804092,  0.08497003, -0.05595911, ..., -0.01711814,
        -0.04232854, -0.05476615],
       [ 0.05068586, -0.007269  , -0.04129183, ..., -0.00616296,
        -0.01938014, -0.08653193],
       [ 0.02608956, -0.08575377,  0.04481799, ..., -0.01034772,
        -0.02418967, -0.00737866]], dtype=float32)>

In [37]:
a = tf.random.normal([5, 784])
b = net(a)

In [38]:
b

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[-0.2379098 , -0.9272796 ,  2.0105586 ,  0.6468125 ,  0.58646905,
        -1.7710775 , -0.0095154 ,  0.25984803, -0.85342455,  1.5438879 ],
       [-2.6107123 ,  1.0393198 ,  0.33591568,  2.6196194 , -1.7328484 ,
        -2.751161  ,  0.86432904, -0.5496489 , -0.7003093 ,  1.8851707 ],
       [-0.61960804,  1.8463048 , -3.0841815 ,  0.4801892 , -3.2569551 ,
        -0.09469625,  1.667824  , -0.243523  ,  0.21756774,  0.7429425 ],
       [ 0.85539806, -1.2348877 ,  0.57816195, -0.68164504, -1.004669  ,
         4.0362997 ,  2.2599244 ,  0.01986712, -1.6694139 , -0.4421531 ],
       [ 0.88143516, -0.43865782,  2.6837292 ,  2.4863276 , -3.763494  ,
        -1.0621133 , -1.7191525 ,  0.08678174, -1.3301022 , -2.7866747 ]],
      dtype=float32)>

In [39]:
a = tf.ones([1, 5, 5, 3])

In [40]:
a[0][0]

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [41]:
a[0][0][1]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [42]:
a[0][0][1][1]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [43]:
a = tf.random.normal([4, 28, 28, 3])

In [44]:
a[1].shape

TensorShape([28, 28, 3])

In [45]:
a[1, 2].shape

TensorShape([28, 3])

In [46]:
a[1, 2, 3].shape

TensorShape([3])

In [47]:
a[1, 2, 3, 2]

<tf.Tensor: shape=(), dtype=float32, numpy=-1.0489656>

In [48]:
a = tf.range(10)
a

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [49]:
a[-1:]  # -> [-1:-1]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([9])>

In [50]:
a[-2:]  # -> [-2: -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 9])>

In [51]:
a[:2]  # -> [0: 2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1])>

In [52]:
a = tf.range(9)
a = tf.reshape(a, (3, 3))
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [53]:
a[:, 0:2], a[:, -1:]

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[0, 1],
        [3, 4],
        [6, 7]])>,
 <tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[2],
        [5],
        [8]])>)

In [54]:
a = tf.random.normal([4, 28, 28, 3])

In [55]:
a[:, :, :, 0].shape, a[:, :, :, :2].shape  # 取图片的R通道，RG双通道

(TensorShape([4, 28, 28]), TensorShape([4, 28, 28, 2]))

In [56]:
a[1, :, :, 0].shape  # 第一张图片的R通道

TensorShape([28, 28])

In [57]:
a[:, 1, :].shape  # 所有图片的第一行所有通道

TensorShape([4, 28, 3])

In [58]:
a[::2].shape  # 取第2，4张图片

TensorShape([2, 28, 28, 3])

In [59]:
a[:, ::2, ::2].shape  #  隔行隔列采样

TensorShape([4, 14, 14, 3])

In [60]:
a = tf.range(9)
a

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [63]:
a[::-1], a[::-2]  # 倒序采样，倒叙隔1行采样

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([8, 7, 6, 5, 4, 3, 2, 1, 0])>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([8, 6, 4, 2, 0])>)

In [68]:
a = tf.reshape(tf.range(27), (3, 3, 3))
a

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])>

In [72]:
tf.gather(a, axis=0, indices=[0, 2]) # 取第一个维度，的第1，3个成员

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])>

In [73]:
tf.gather(a, axis=1, indices=[0, 1]) # 第二个维度，的第1，2个成员

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 9, 10, 11],
        [12, 13, 14]],

       [[18, 19, 20],
        [21, 22, 23]]])>

In [75]:
tf.gather(a, axis=2, indices=[1, 0])

<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[ 1,  0],
        [ 4,  3],
        [ 7,  6]],

       [[10,  9],
        [13, 12],
        [16, 15]],

       [[19, 18],
        [22, 21],
        [25, 24]]])>

In [90]:
a

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])>

In [92]:
tf.gather_nd(a, [2, 2]), a[2, 2] # 取 a[2, 2]共一个样本

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([24, 25, 26])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([24, 25, 26])>)

In [94]:
tf.gather_nd(a, [[1, 1], [1, 2], [2, 0]]), a[1, 1], a[1, 2], a[2, 0]
# 取a[1, 1], a[1, 2], a[2, 0] 共三个样本

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20]])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([12, 13, 14])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([15, 16, 17])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([18, 19, 20])>)

In [96]:
tf.gather_nd(a, [[1, 1, 0], [1, 2, 1], [2, 0, 2], [2, 0, 1]])
# 取a[1, 1, 0], a[1, 2, 1], a[2, 0, 2], a[2, 0, 1] 共4个样本

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([12, 16, 20, 19])>

In [97]:
a[1, 1, 0], a[1, 2, 1], a[2, 0, 2], a[2, 0, 1]

(<tf.Tensor: shape=(), dtype=int32, numpy=12>,
 <tf.Tensor: shape=(), dtype=int32, numpy=16>,
 <tf.Tensor: shape=(), dtype=int32, numpy=20>,
 <tf.Tensor: shape=(), dtype=int32, numpy=19>)

In [98]:
a

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])>

In [100]:
tf.gather_nd(a, [[[0, 0], [1, 0], [2, 0]]])

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20]]])>

In [109]:
a=tf.ones([4, 28, 28, 3])

In [110]:
tf.boolean_mask(a, mask=[True, True, False, True]).shape # 取0，1，3张图片

TensorShape([3, 28, 28, 3])

In [111]:
tf.boolean_mask(a, mask=[True, True, False], axis=3).shape # 取 RG通道

TensorShape([4, 28, 28, 2])

In [121]:
a=tf.reshape(tf.range(24), [2, 3, 4])
a

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

In [122]:
tf.boolean_mask(a, mask=[[True, False, False], [True, True, False]])

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])>