In [1]:
import os

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import datasets, layers, optimizers

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

## 13.1 WHERE

In [4]:
a = tf.random.normal([3, 3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.21633968, -1.0504389 ,  1.12904   ],
       [-1.8362275 , -1.0495322 , -2.850246  ],
       [-0.13719033,  0.5125932 , -0.44809896]], dtype=float32)>

In [5]:
mask = a > 0

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[False, False,  True],
       [False, False, False],
       [False,  True, False]])>

In [7]:
tf.boolean_mask(a, mask) # 取得对应元素为True的值

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.12904  , 0.5125932], dtype=float32)>

In [12]:
indices = tf.where(mask) # 取得对应元素为True的值的坐标
indices

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[0, 2],
       [2, 1]], dtype=int64)>

In [10]:
tf.gather_nd(a, indices) # 取得对应元素为True的值

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.12904  , 0.5125932], dtype=float32)>

In [13]:
mask

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[False, False,  True],
       [False, False, False],
       [False,  True, False]])>

In [16]:
A = tf.zeros([3, 3])
B = tf.ones([3, 3])

In [17]:
tf.where(mask, A, B)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 0.],
       [1., 1., 1.],
       [1., 0., 1.]], dtype=float32)>

## 13.2 scatter_nd

In [19]:
indices = tf.constant([[4], [3], [1], [7]])
updates = tf.constant([9, 10, 11, 12])
shape = tf.constant([8])

In [20]:
tf.scatter_nd(indices, updates, shape)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 0, 11,  0, 10,  9,  0,  0, 12])>

## 13.3 meshgrid

In [24]:
y = tf.linspace(-2., 2, 5)
y

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([-2., -1.,  0.,  1.,  2.], dtype=float32)>

In [26]:
x = tf.linspace(-2., 2, 5)
x

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([-2., -1.,  0.,  1.,  2.], dtype=float32)>

In [27]:
px, py = tf.meshgrid(x, y)
px, py

(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.]], dtype=float32)>,
 <tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[-2., -2., -2., -2., -2.],
        [-1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.,  2.]], dtype=float32)>)

In [30]:
tf.stack([px, py], axis=2)

<tf.Tensor: shape=(5, 5, 2), dtype=float32, numpy=
array([[[-2., -2.],
        [-1., -2.],
        [ 0., -2.],
        [ 1., -2.],
        [ 2., -2.]],

       [[-2., -1.],
        [-1., -1.],
        [ 0., -1.],
        [ 1., -1.],
        [ 2., -1.]],

       [[-2.,  0.],
        [-1.,  0.],
        [ 0.,  0.],
        [ 1.,  0.],
        [ 2.,  0.]],

       [[-2.,  1.],
        [-1.,  1.],
        [ 0.,  1.],
        [ 1.,  1.],
        [ 2.,  1.]],

       [[-2.,  2.],
        [-1.,  2.],
        [ 0.,  2.],
        [ 1.,  2.],
        [ 2.,  2.]]], dtype=float32)>