In [2]:
import os

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import datasets, layers, optimizers

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

## 11.1 tf.pad

In [4]:
a = tf.random.uniform([3, 3], maxval=10, dtype=tf.int32)
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 4, 4],
       [9, 4, 8],
       [0, 4, 3]])>

In [9]:
tf.pad(a, [[1, 1], [1, 1]]) # 行 列左右各padding 1行

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 4, 4, 4, 0],
       [0, 9, 4, 8, 0],
       [0, 0, 4, 3, 0],
       [0, 0, 0, 0, 0]])>

In [10]:
a = tf.random.normal([4, 28, 28, 3]) # 行 列左右各padding 2行

In [13]:
tf.pad(a, [[0, 0], [2, 2], [2, 2], [0, 0]]).shape

TensorShape([4, 32, 32, 3])

## tf.tile

In [14]:
a = tf.random.uniform([3, 3], maxval=10, dtype=tf.int32)
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[9, 3, 1],
       [8, 5, 1],
       [6, 4, 1]])>

In [15]:
tf.tile(a, [1, 2])  # 第一个维度为原来的1倍，第二个维度为原来的2倍

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[9, 3, 1, 9, 3, 1],
       [8, 5, 1, 8, 5, 1],
       [6, 4, 1, 6, 4, 1]])>

In [16]:
tf.tile(a, [2, 2]) # 先复制小维度

<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
array([[9, 3, 1, 9, 3, 1],
       [8, 5, 1, 8, 5, 1],
       [6, 4, 1, 6, 4, 1],
       [9, 3, 1, 9, 3, 1],
       [8, 5, 1, 8, 5, 1],
       [6, 4, 1, 6, 4, 1]])>