In [1]:
import os

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import datasets, layers, optimizers

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

## 9.1 tf.sort/tf.argsort

排序/排序返回下标

In [5]:
a = tf.random.shuffle(tf.range(5))
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 3, 4, 1, 2])>

In [8]:
s = tf.sort(a, direction='DESCENDING') # 排序
s

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 3, 2, 1, 0])>

In [13]:
idx = tf.argsort(a, direction='DESCENDING') # 排序后返回，源Tensor顺序下标
idx

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 1, 4, 3, 0])>

In [14]:
tf.gather(a, idx) # 使用gather可以得到排序后的s

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 3, 2, 1, 0])>

In [24]:
a = tf.random.uniform([3, 3], maxval=10, dtype=tf.int32)
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 1, 0],
       [6, 3, 6],
       [8, 2, 7]])>

In [26]:
tf.sort(a) # 默认对最后一个维度-1排序

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 7],
       [3, 6, 6],
       [2, 7, 8]])>

In [29]:
tf.sort(a, axis=0)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 1, 0],
       [7, 2, 6],
       [8, 3, 7]])>

In [30]:
tf.argsort(a)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 1, 0],
       [1, 0, 2],
       [1, 2, 0]])>

## 10.2 top_k

In [32]:
a = tf.random.uniform([3, 3], maxval=10, dtype=tf.int32)
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[8, 6, 2],
       [9, 3, 2],
       [0, 8, 9]])>

In [33]:
res = tf.math.top_k(a, 2)

In [35]:
res.indices, res.values
# indices 为top_k的下标
# values 为具体的前k个最大值

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[0, 1],
        [0, 1],
        [2, 1]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[8, 6],
        [9, 3],
        [9, 8]])>)

In [36]:
prob = tf.constant([
    [0.1, 0.2, 0.7],
    [0.2, 0.7, 0.1],
])
target = tf. constant([2, 0])

In [45]:
def accurac(output: tf.Tensor, target: tf.Tensor, topk=(1,)):
    maxk = max(topk)
    batch_size = target.shape[0]
    
    pred = tf.math.top_k(output, maxk).indices
    pred = tf. transpose(pred, perm=[1, 0])
    target_ = tf.broadcast_to(target, pred.shape)
    correct = tf.equal(pred, target_)
    
    res = []
    for k in topk:
        correct_k = tf.cast(tf.reshape( correct[:k], [-1]), dtype=tf.float32)
        correct_k = tf.reduce_sum(correct_k)
        acc = float(correct_k / batch_size)
        res.append(acc)
    
    return res

In [57]:
accurac(prob, target, topk=[1,])

[0.5]